//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Planet.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IPlanetListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class PlanetBaseListener : IPlanetListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] PlanetParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] PlanetParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.topLevelDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTopLevelDecl([NotNull] PlanetParser.TopLevelDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.topLevelDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTopLevelDecl([NotNull] PlanetParser.TopLevelDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.functionDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDecl([NotNull] PlanetParser.FunctionDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.functionDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDecl([NotNull] PlanetParser.FunctionDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.paramList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamList([NotNull] PlanetParser.ParamListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.paramList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamList([NotNull] PlanetParser.ParamListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] PlanetParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] PlanetParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] PlanetParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] PlanetParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.varDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDecl([NotNull] PlanetParser.VarDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.varDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDecl([NotNull] PlanetParser.VarDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.importStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportStmt([NotNull] PlanetParser.ImportStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.importStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportStmt([NotNull] PlanetParser.ImportStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.ifStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStmt([NotNull] PlanetParser.IfStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.ifStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStmt([NotNull] PlanetParser.IfStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.whileStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStmt([NotNull] PlanetParser.WhileStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.whileStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStmt([NotNull] PlanetParser.WhileStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.returnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStmt([NotNull] PlanetParser.ReturnStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.returnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStmt([NotNull] PlanetParser.ReturnStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.commandStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommandStmt([NotNull] PlanetParser.CommandStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.commandStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommandStmt([NotNull] PlanetParser.CommandStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.assignStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignStmt([NotNull] PlanetParser.AssignStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.assignStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignStmt([NotNull] PlanetParser.AssignStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.lvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLvalue([NotNull] PlanetParser.LvalueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.lvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLvalue([NotNull] PlanetParser.LvalueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.exprStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprStmt([NotNull] PlanetParser.ExprStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.exprStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprStmt([NotNull] PlanetParser.ExprStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.emptyStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyStmt([NotNull] PlanetParser.EmptyStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.emptyStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyStmt([NotNull] PlanetParser.EmptyStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.eos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEos([NotNull] PlanetParser.EosContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.eos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEos([NotNull] PlanetParser.EosContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] PlanetParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] PlanetParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.logicOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicOr([NotNull] PlanetParser.LogicOrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.logicOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicOr([NotNull] PlanetParser.LogicOrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.logicAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicAnd([NotNull] PlanetParser.LogicAndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.logicAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicAnd([NotNull] PlanetParser.LogicAndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.equality"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEquality([NotNull] PlanetParser.EqualityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.equality"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEquality([NotNull] PlanetParser.EqualityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.relation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelation([NotNull] PlanetParser.RelationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.relation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelation([NotNull] PlanetParser.RelationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.add"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdd([NotNull] PlanetParser.AddContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.add"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdd([NotNull] PlanetParser.AddContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.mul"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMul([NotNull] PlanetParser.MulContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.mul"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMul([NotNull] PlanetParser.MulContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.unary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary([NotNull] PlanetParser.UnaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.unary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary([NotNull] PlanetParser.UnaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.postfix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostfix([NotNull] PlanetParser.PostfixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.postfix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostfix([NotNull] PlanetParser.PostfixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtom([NotNull] PlanetParser.AtomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtom([NotNull] PlanetParser.AtomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.callSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallSuffix([NotNull] PlanetParser.CallSuffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.callSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallSuffix([NotNull] PlanetParser.CallSuffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.argList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgList([NotNull] PlanetParser.ArgListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.argList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgList([NotNull] PlanetParser.ArgListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.indexer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexer([NotNull] PlanetParser.IndexerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.indexer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexer([NotNull] PlanetParser.IndexerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] PlanetParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] PlanetParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.stringLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringLiteral([NotNull] PlanetParser.StringLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.stringLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringLiteral([NotNull] PlanetParser.StringLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.arrayLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayLiteral([NotNull] PlanetParser.ArrayLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.arrayLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayLiteral([NotNull] PlanetParser.ArrayLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.nbtObject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNbtObject([NotNull] PlanetParser.NbtObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.nbtObject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNbtObject([NotNull] PlanetParser.NbtObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.nbtPair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNbtPair([NotNull] PlanetParser.NbtPairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.nbtPair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNbtPair([NotNull] PlanetParser.NbtPairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.nbtKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNbtKey([NotNull] PlanetParser.NbtKeyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.nbtKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNbtKey([NotNull] PlanetParser.NbtKeyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.nbtValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNbtValue([NotNull] PlanetParser.NbtValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.nbtValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNbtValue([NotNull] PlanetParser.NbtValueContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
