//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Planet.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="PlanetParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IPlanetListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] PlanetParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] PlanetParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.topLevelDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopLevelDecl([NotNull] PlanetParser.TopLevelDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.topLevelDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopLevelDecl([NotNull] PlanetParser.TopLevelDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.functionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDecl([NotNull] PlanetParser.FunctionDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.functionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDecl([NotNull] PlanetParser.FunctionDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamList([NotNull] PlanetParser.ParamListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamList([NotNull] PlanetParser.ParamListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] PlanetParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] PlanetParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] PlanetParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] PlanetParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDecl([NotNull] PlanetParser.VarDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDecl([NotNull] PlanetParser.VarDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.importStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportStmt([NotNull] PlanetParser.ImportStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.importStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportStmt([NotNull] PlanetParser.ImportStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.ifStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStmt([NotNull] PlanetParser.IfStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.ifStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStmt([NotNull] PlanetParser.IfStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.whileStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStmt([NotNull] PlanetParser.WhileStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.whileStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStmt([NotNull] PlanetParser.WhileStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStmt([NotNull] PlanetParser.ReturnStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStmt([NotNull] PlanetParser.ReturnStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.commandStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommandStmt([NotNull] PlanetParser.CommandStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.commandStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommandStmt([NotNull] PlanetParser.CommandStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.assignStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignStmt([NotNull] PlanetParser.AssignStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.assignStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignStmt([NotNull] PlanetParser.AssignStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLvalue([NotNull] PlanetParser.LvalueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLvalue([NotNull] PlanetParser.LvalueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.exprStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprStmt([NotNull] PlanetParser.ExprStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.exprStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprStmt([NotNull] PlanetParser.ExprStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.emptyStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyStmt([NotNull] PlanetParser.EmptyStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.emptyStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyStmt([NotNull] PlanetParser.EmptyStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.eos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEos([NotNull] PlanetParser.EosContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.eos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEos([NotNull] PlanetParser.EosContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] PlanetParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] PlanetParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.logicOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicOr([NotNull] PlanetParser.LogicOrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.logicOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicOr([NotNull] PlanetParser.LogicOrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.logicAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicAnd([NotNull] PlanetParser.LogicAndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.logicAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicAnd([NotNull] PlanetParser.LogicAndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.equality"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEquality([NotNull] PlanetParser.EqualityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.equality"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEquality([NotNull] PlanetParser.EqualityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.relation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelation([NotNull] PlanetParser.RelationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.relation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelation([NotNull] PlanetParser.RelationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.add"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdd([NotNull] PlanetParser.AddContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.add"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdd([NotNull] PlanetParser.AddContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.mul"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMul([NotNull] PlanetParser.MulContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.mul"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMul([NotNull] PlanetParser.MulContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary([NotNull] PlanetParser.UnaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary([NotNull] PlanetParser.UnaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.postfix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfix([NotNull] PlanetParser.PostfixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.postfix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfix([NotNull] PlanetParser.PostfixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom([NotNull] PlanetParser.AtomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom([NotNull] PlanetParser.AtomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.callSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallSuffix([NotNull] PlanetParser.CallSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.callSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallSuffix([NotNull] PlanetParser.CallSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgList([NotNull] PlanetParser.ArgListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgList([NotNull] PlanetParser.ArgListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.indexer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexer([NotNull] PlanetParser.IndexerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.indexer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexer([NotNull] PlanetParser.IndexerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] PlanetParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] PlanetParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringLiteral([NotNull] PlanetParser.StringLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringLiteral([NotNull] PlanetParser.StringLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.arrayLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayLiteral([NotNull] PlanetParser.ArrayLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.arrayLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayLiteral([NotNull] PlanetParser.ArrayLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.nbtObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNbtObject([NotNull] PlanetParser.NbtObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.nbtObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNbtObject([NotNull] PlanetParser.NbtObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.nbtPair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNbtPair([NotNull] PlanetParser.NbtPairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.nbtPair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNbtPair([NotNull] PlanetParser.NbtPairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.nbtKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNbtKey([NotNull] PlanetParser.NbtKeyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.nbtKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNbtKey([NotNull] PlanetParser.NbtKeyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlanetParser.nbtValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNbtValue([NotNull] PlanetParser.NbtValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlanetParser.nbtValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNbtValue([NotNull] PlanetParser.NbtValueContext context);
}
